[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.11"

[dev-dependencies]
solana-program = "2.0.11"
solana-sdk = "2.0.11"

[lib]
crate-type = ["cdylib", "lib"]
